### ISSUE TITLE
 pthread barriers are not implemented in OS X

### ISSUE THREAD

**Issue by bohutang** [pmwkaa/ioarena#10]
@leo-yuriev 
@pmwkaa 

Ioarena is broken on OS X, errors are as follow:

```
src/ia.h:16:2: error: unknown type name 'pthread_barrier_t'
  pthread_barrier_t barrier_start;
```

Here is an  implementation:
http://blog.albertarmea.com/post/47089939939/using-pthreadbarrier-on-mac-os-x

**Comment by erthink** [comment]
Could someone check on a Mac ?

**Comment by bohutang** [comment]
@leo-yuriev 
Y.
Sophia & nessDB & others SEs is cross-platform compatible.
Most hackers prefer Macs.

**Comment by erthink** [comment]
OK ;)

Please close issue if done.

**Comment by erthink** [comment]
Could we close this issue and merge https://github.com/pmwkaa/ioarena/commit/b8854d4b164591cb62a97f67a6dc3645b26f4b39 (the `devel` branch) into master ?

**Comment by bohutang** [comment]
pthread_barrier_t is OK.
But still has problem with clock_gettime:

```
ioarena/src/ia_histogram.c:29:2: error: implicit declaration of function 'clock_gettime' [-Werror=implicit-function-declaration]
  int rc = clock_gettime(CLOCK_ID, &ts);
  ^
ioarena/src/ia_histogram.c:16:19: error: 'CLOCK_REALTIME' undeclared (first use in this function)
 # define CLOCK_ID CLOCK_REALTIME
                   ^
ioarena/src/ia_histogram.c:29:25: note: in expansion of macro 'CLOCK_ID'
  int rc = clock_gettime(CLOCK_ID, &ts);
                         ^
```

**Comment by erthink** [comment]
I'm closing this issue, but added the https://github.com/pmwkaa/ioarena/issues/13
