### ISSUE TITLE
Makefiles are Linux-specific, fail on other platforms

### ISSUE THREAD

**Issue by snej** [pmwkaa/ioarena#16]
The cmake scripts in `cmake/Build*.cmake` are hardcoded to assume that the libraries end up with a filename suffix of `.so`. That's true for Linux, but not Mac OS (or iOS) where the default suffix is `.dylib`. (I don't develop for BSD or Windows, but those might use different suffixes too.)

For example, `cmake/BuildLevelDB.cmake` has 3 lines like:

```
OUTPUT ${PROJECT_BINARY_DIR}/db/leveldb/libleveldb.so
```

The result is link errors building the `ioarena` binary, since the `*.so` files can't be found.

I know nothing about Cmake, so I don't have a fix to submit. I was able to work around the problem by replacing `.so` with `.dylib` in my local copies of the Cmake files.

**Comment by erthink** [comment]
Please check the devel branch.
