### ISSUE TITLE
nessDB driver is invalid

### ISSUE THREAD

**Issue by erthink** [pmwkaa/ioarena#29]
Briefly, it NOT implements the basic mandatory operations.
It just do nothing: https://github.com/pmwkaa/ioarena/blob/892c50e4c40a109c8f6c3c73ca4b59fa8d1d4e4d/src/ia_nessdb.c#L135-L138

Moreover, the nessDB API don't provide/export such functions.
In other words, nessDB is NOT a ready engine, which could be used or tested here.

So, I suggest to drop the nessDB driver from the ioarena (with the hope that it will be added again when unacceptable flaws will be eliminated).

On the other hand, maybe @BohuTANG decide to fix this in a few days?

**Comment by bohutang** [comment]
Sorry, nessDB remained unchanged for a long time.
Please remove it from ioarena until it's alive again, thanks.
