### ISSUE TITLE
nessdb driver should be updated (or removed)

### ISSUE THREAD

**Issue by erthink** [pmwkaa/ioarena#8]
nessdb driver now is just a stub with obsolete interface, so it should be updated or removed.

**Comment by bohutang** [comment]
nessDB driver is ready, commit is:
https://github.com/pmwkaa/ioarena/commit/19d6e2df87ada227d751bcb87eaee16ae51afeb9

BTW, ioarena needs so many memory for itself, it's terrible for a benchmark framework.

**Comment by erthink** [comment]
@BohuTANG, yes, the "random pool" take a lot of memory - see https://github.com/pmwkaa/ioarena/issues/6

Currently I don't have enough time and motivation to do it, because of https://github.com/ReOpen/ReOpenLDAP/issues/65 and the other bullshit comes from openldap.
